# Min / max battery percent allowed
[BATTERY_RANGE]
min_percent = 30
max_percent = 80

# Domain to ping
[PING_DOMAIN]
ping_domain = 

# Hotkeys
[HOTKEYS]
hibernation = True

# Kasa / Tapo (TP-Link) smart plug devices
[KASA]
kasa_email = 
kasa_password = 
kasa_device_1 = 
