# Min/max battery percent allowed
[BATTERY_RANGE]
min_percent = 30
max_percent = 80

# Domain to ping
[PING_DOMAIN]
ping_domain = 

# on/off webhook urls
[WEBHOOKS]
on_url = 
off_url = 

# Kasa smart plug device
[KASA]
kasa_email = 
kasa_password = 
kasa_device_name = 

[HOTKEYS]
hibernation = True
